### ISSUE TITLE
Use service credentials for Remote API authentication

### ISSUE THREAD

**Issue by iperdomo** [akvo/akvo-commons#13]
On Dec 8th there will be the first attempt to disable username/password authentication for Remote API, and then disabled completely by Jan 2016.
https://cloud.google.com/appengine/docs/deprecations/clientlogin

We need to be prepared to support OAuth 2 based authentication. The easiest way is to create [Service Accounts](https://developers.google.com/identity/protocols/OAuth2ServiceAccount)

**Comment by jonase** [comment]
Closing this one as done as part of the 0.4.0 release
